
## Spring Security oAuth2 configurations
spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 3199779683668880
            clientSecret: adeb3199b01d45be0ebc5b2c839bb9ae
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
      resource:
        userInfoUri: https://graph.facebook.com/me





