server:
  max-http-header-size: 65536
  port: 8080

h2:
  db:
    port: 8082

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
  datasource:
    url: jdbc:h2:file:./build/db/h2;MODE=LEGACY;DB_CLOSE_ON_EXIT=FALSE
    spurldev: jdbc:h2:tcp://localhost:\${h2.db.port}/./build/db/h2;MODE=LEGACY;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

